name: EDFacts File Progress Report
description: Submit updates on EDFacts file development progress.
title: "[EDFacts Progress]: "
labels: ["EDFacts", "progress"]
body:
  - type: markdown
    attributes:
      value: |
        ## EDFacts File Progress Report
        Please provide the necessary details to track file progress.

  - type: input
    id: file-spec-number
    attributes:
      label: File Specification Number
      description: Enter the EDFacts file specification number (e.g., FS005).
      placeholder: FS###
    validations:
      required: true

  - type: input
    id: file-name
    attributes:
      label: File Name
      description: Provide the name of the EDFacts file (e.g., "Child Count").
      placeholder: File name here
    validations:
      required: true

  - type: textarea
    id: progress
    attributes:
      label: File Development Progress
      description: Describe the progress made on this file (e.g., status, next steps, blockers).
      placeholder: Update on the development progress.
    validations:
      required: true

  - type: dropdown
    id: state-organization
    attributes:
      label: State or Organization
      description: Select the state or organization responsible for this file.
      options:
        - Alabama
        - Alaska
        - Arizona
        - Arkansas
        - California
        - Colorado
        - Connecticut
        - Delaware
        - Florida
        - Georgia
        - Hawaii
        - Idaho
        - Illinois
        - Indiana
        - Iowa
        - Kansas
        - Kentucky
        - Louisiana
        - Maine
        - Maryland
        - Massachusetts
        - Michigan
        - Minnesota
        - Mississippi
        - Missouri
        - Montana
        - Nebraska
        - Nevada
        - New Hampshire
        - New Jersey
        - New Mexico
        - New York
        - North Carolina
        - North Dakota
        - Ohio
        - Oklahoma
        - Oregon
        - Pennsylvania
        - Rhode Island
        - South Carolina
        - South Dakota
        - Tennessee
        - Texas
        - Utah
        - Vermont
        - Virginia
        - Washington
        - West Virginia
        - Wisconsin
        - Wyoming
        - CNMI (Commonwealth of the Northern Mariana Islands)
        - Other Organization
    validations:
      required: true

  - type: textarea
    id: additional-comments
    attributes:
      label: Additional Comments
      description: Add any other relevant details or comments about this file.
      placeholder: Additional notes here.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com/code-of-conduct).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true