name: EDFacts File Progress Report
description: Submit updates on EDFacts file development progress.
title: "[EDFacts Progress]: "
labels: ["EDFacts", "progress", "QA"]
body:
  - type: markdown
    attributes:
      value: |
        ## EDFacts File Progress Report
        Please complete the form below to log progress and meet acceptance criteria.

  - type: dropdown
    id: file-spec-dropdown
    attributes:
      label: File Spec Number and File Name
      description: Select the EDFacts File Specification Number and File Name.
      options:
        - FS005 - Child Count
        - FS006 - Staff Count
        - FS007 - Assessment Participation
        - FS009 - Graduation Rate
        - FS013 - Dropout Rate
        - FS088 - Discipline Incidents
        - FS141 - Suspension Expulsion
        - FS143 - Educational Environment
        - FS185 - Exiting Special Education
        - FS203 - Post-School Outcomes
        - Other (Specify in comments)
      validations:
        required: true

  - type: textarea
    id: progress
    attributes:
      label: File Development Progress
      description: Describe the progress made on this file (e.g., status, blockers, next steps).
      placeholder: Provide details about the development progress here.
    validations:
      required: true

  - type: dropdown
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What part of the acceptance criteria is being addressed?
      options:
        - Setup
        - QA
        - Migration Steps
        - Requires updating of Test Case(s)
        - Identify any documentation updates
        - Impact to OSC
      validations:
        required: true

  - type: dropdown
    id: test-case-update
    attributes:
      label: Requires Updating of Test Case(s)?
      description: Does this update require changes to test cases?
      options:
        - Yes
        - No
      validations:
        required: true

  - type: input
    id: documentation-updates
    attributes:
      label: Documentation Updates
      description: Specify any documentation updates needed (e.g., guide names or pages).
      placeholder: Documentation details here.
    validations:
      required: false

  - type: input
    id: osc-impact
    attributes:
      label: Impact to OSC
      description: Describe the impact to OSC, and include the OSC ticket number if applicable.
      placeholder: e.g., OSC-12345
    validations:
      required: false

  - type: dropdown
    id: state-organization
    attributes:
      label: State or Organization
      description: Select the state or organization responsible for this file.
      options:
        - Alabama
        - Alaska
        - Arizona
        - Arkansas
        - California
        - Colorado
        - Connecticut
        - Delaware
        - Florida
        - Georgia
        - Hawaii
        - Idaho
        - Illinois
        - Indiana
        - Iowa
        - Kansas
        - Kentucky
        - Louisiana
        - Maine
        - Maryland
        - Massachusetts
        - Michigan
        - Minnesota
        - Mississippi
        - Missouri
        - Montana
        - Nebraska
        - Nevada
        - New Hampshire
        - New Jersey
        - New Mexico
        - New York
        - North Carolina
        - North Dakota
        - Ohio
        - Oklahoma
        - Oregon
        - Pennsylvania
        - Rhode Island
        - South Carolina
        - South Dakota
        - Tennessee
        - Texas
        - Utah
        - Vermont
        - Virginia
        - Washington
        - West Virginia
        - Wisconsin
        - Wyoming
        - CNMI (Commonwealth of the Northern Mariana Islands)
        - Other Organization
      validations:
        required: true

  - type: textarea
    id: additional-comments
    attributes:
      label: Additional Comments
      description: Add any other relevant details or comments about this file.
      placeholder: Additional notes here.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com/code-of-conduct).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
