name: Documentation Update
description: Report issues with documentation or suggest improvements.
title: "[Docs]: "
labels: ["documentation", "content"]
body:
  - type: markdown
    attributes:
      value: |
        ## Documentation Update  
        Use this form to propose fixes or improvements to the documentation.  
        
        📚 **Relevant Documentation Links**:  
        - [GitBook Home Page](https://your-gitbook-home-link)  
        - [Significant Disproportionality Guide](https://your-gitbook-link)  
        - [Set Up Guide](https://your-gitbook-link)  

  - type: textarea
    id: current-issue
    attributes:
      label: Current Documentation Issue
      description: Describe the problem with the current documentation.
      placeholder: Describe what’s wrong or missing.
    validations:
      required: true

  - type: textarea
    id: proposed-change
    attributes:
      label: Proposed Change
      description: Describe the update or improvement you’re suggesting.
      placeholder: Describe the new content or fix here.

  - type: input
    id: page-link
    attributes:
      label: Documentation Page Link
      description: Provide a link to the affected GitBook documentation page.
      placeholder: Paste the GitBook page URL here.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this update?
      options:
        - Low
        - Medium
        - High
      default: 1 # Medium priority

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow the Code of Conduct.
          required: true

