name: Feature Request
description: Suggest a new feature or improvement.
title: "[Feature]: "
labels: ["enhancement", "feature"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request  
        Propose a new feature or improvement for the project.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Clearly describe the feature or improvement you'd like to see.
      placeholder: Describe the feature here.
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How will this feature solve a problem or improve the project?
      placeholder: Describe the benefit or use case for this feature.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Low
        - Medium
        - High
      default: 1 # Medium is the second option (index starts at 0)

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Context
      description: Add any other context, links, or screenshots about the feature.
      placeholder: Include links, screenshots, or related issues here.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow the Code of Conduct.
          required: true

