name: Feature Request
description: Suggest a new feature or improvement.
title: "[Feature]: "
labels: ["enhancement", "feature"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Propose a new feature or improvement.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Clearly describe the feature you'd like to see.
      placeholder: Describe the new feature here.
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How will this feature solve a problem or improve the project?
      placeholder: Describe the benefit or problem this feature solves.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Low
        - Medium
        - High
      default: Medium

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Context
      description: Add any other context, links, or screenshots about the feature.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow the Code of Conduct.
          required: true
