name: Completion of Generate Ticket
description: Create or update a ticket for non-IDEA file specs in the Completion of Generate repo.
title: "[Pilot FS ###]: "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        ## Completion of Generate Ticket
        Use this template to provide details about the non-IDEA file spec you're working on.

  - type: textarea
    id: file-spec-details
    attributes:
      label: File Specification Details
      description: Provide details about the file spec, including challenges or key milestones.
      placeholder: Enter details about the file spec here.

  - type: dropdown
    id: status
    attributes:
      label: Status
      description: Select the current status of this ticket.
      options:
        - No Status
        - Risks
        - To-Do
        - In Progress
        - Testing
        - Done
 
  - type: checkboxes
    id: states
    attributes:
      label: Associated State(s)
      description: Select the state(s) or entity/entities working on this ticket.
      options:
        - label: Alabama
        - label: Alaska
        - label: Arizona
        - label: Arkansas
        - label: California
        - label: Colorado
        - label: Connecticut
        - label: Delaware
        - label: Florida
        - label: Georgia
        - label: Hawaii
        - label: Idaho
        - label: Illinois
        - label: Indiana
        - label: Iowa
        - label: Kansas
        - label: Kentucky
        - label: Louisiana
        - label: Maine
        - label: Maryland
        - label: Massachusetts
        - label: Michigan
        - label: Minnesota
        - label: Mississippi
        - label: Missouri
        - label: Montana
        - label: Nebraska
        - label: Nevada
        - label: New Hampshire
        - label: New Jersey
        - label: New Mexico
        - label: New York
        - label: North Carolina
        - label: North Dakota
        - label: Ohio
        - label: Oklahoma
        - label: Oregon
        - label: Pennsylvania
        - label: Rhode Island
        - label: South Carolina
        - label: South Dakota
        - label: Tennessee
        - label: Texas
        - label: Utah
        - label: Vermont
        - label: Virginia
        - label: Washington
        - label: West Virginia
        - label: Wisconsin
        - label: Wyoming
        - label: American Samoa
        - label: Commonwealth of the Northern Mariana Islands
        - label: District of Columbia
        - label: Federated States of Micronesia
        - label: Guam
        - label: Marshall Islands
        - label: Palau
        - label: Puerto Rico
        - label: U.S. Virgin Islands
        - label: Bureau of Indian Education
