name: Update Issue Status Based on Project Column

on:
  project_card:
    types: [moved]

permissions:
  contents: write
  issues: write

jobs:
  update-status:
    runs-on: ubuntu-latest
    steps:
      - name: Log Event Payload
        run: echo "${{ toJson(github.event) }}"

      - name: Update Issue Status
        uses: actions/github-script@v6
        with:
          script: |
            const projectCard = context.payload.project_card;
            if (!projectCard) {
              throw new Error("No project_card data in event payload.");
            }

            const columnId = projectCard.column_id; // Column ID from the payload
            const contentUrl = projectCard.content_url; // URL of the linked issue or PR
            
            if (!contentUrl) {
              throw new Error("No content_url found. Ensure the card is linked to an issue.");
            }

            const issueNumber = contentUrl.split('/').pop();
            const repoOwner = context.repo.owner;
            const repoName = context.repo.repo;

            const columnToLabelMap = {
              "1234567890": "no status",
              "0987654321": "risks",
              "1122334455": "to-do",
              "5566778899": "in progress",
              "6677889900": "testing",
              "7788990011": "done"
            };

            const labelToApply = columnToLabelMap[columnId] || null;
            if (labelToApply) {
              await github.rest.issues.addLabels({
                owner: repoOwner,
                repo: repoName,
                issue_number: issueNumber,
                labels: [labelToApply]
              });
            }
