name: Update Issue Status Based on Project Column

on:
  project_card:
    types: [moved, created, edited]

permissions:
  contents: write
  issues: write

jobs:
  update-status:
    runs-on: ubuntu-latest
    steps:
      - name: Log Event Payload
        run: echo "${{ toJson(github.event) }}"

      - name: Update Issue Status
        uses: actions/github-script@v6
        with:
          script: |
            const projectCard = context.payload.project_card;
            const contentUrl = projectCard.content_url; // URL of the linked issue or PR
            
            if (!contentUrl) {
              throw new Error("No content_url found. Ensure the card is linked to an issue.");
            }

            const issueNumber = contentUrl.split('/').pop();
            const repoOwner = context.repo.owner;
            const repoName = context.repo.repo;

            // Map column names to labels
            const columnToLabelMap = {
              "No Status": "no status",
              "Risks": "risks",
              "To-Do": "to-do",
              "In Progress": "in progress",
              "Testing": "testing",
              "Done": "done"
            };

            const columnName = projectCard.column_name; // Column name from the payload
            const labelToApply = columnToLabelMap[columnName] || null;

            if (labelToApply) {
              await github.rest.issues.addLabels({
                owner: repoOwner,
                repo: repoName,
                issue_number: issueNumber,
                labels: [labelToApply]
              });
            }
