name: Update Issue Status Based on Project Column

on:
  workflow_dispatch:
  project_card:
    types: [moved]

permissions:
  issues: write
  projects: read

jobs:
  update-status:
    runs-on: ubuntu-latest
    steps:
      - name: Update Issue Status
        uses: actions/github-script@v6
        with:
          script: |
            const projectCard = context.payload.project_card;
            const columnName = projectCard.column_name;
            const contentUrl = projectCard.content_url;

            if (contentUrl && contentUrl.includes('/issues/')) {
              const issueNumber = contentUrl.split('/').pop();
              const repoOwner = context.repo.owner;
              const repoName = context.repo.repo;

              const columnToLabelMap = {
                "No Status": "no status",
                "Risks": "risks",
                "To-Do": "to-do",
                "In Progress": "in progress",
                "Testing": "testing",
                "Done": "done"
              };

              const labelToApply = columnToLabelMap[columnName] || null;

              if (labelToApply) {
                await github.rest.issues.addLabels({
                  owner: repoOwner,
                  repo: repoName,
                  issue_number: issueNumber,
                  labels: [labelToApply]
                });
              }
            }

